name: wt_google_sheets
description: "Dart library that reads and writes data to Google Sheets."
version: 0.0.1+1
publish_to: none
homepage: https://github.com/tmcmaster/wt_google_sheet

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection:
  flutter:
    sdk: flutter
  flutter_riverpod:
  freezed_annotation: ^2.4.4
  gsheets:
  intl:
  wt_logging:
    git:
      url: git@github.com:tmcmaster/wt_logging.git
  wt_models:
    git:
      url: git@github.com:tmcmaster/wt_models.git
  wt_state:
    git:
      url: git@github.com:tmcmaster/wt_state.git

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints:
  freezed: ^2.4.1
  json_serializable:

dependency_overrides:
  wt_state:
    path: ../wt_state